name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ubah ke nama branch Anda jika berbeda

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Sesuaikan dengan versi Node.js yang Anda gunakan

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure git
        run: |
          git config --global user.email "abdillahag98@gmail.com"
          git config --global user.name "abdillah98"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g gh-pages
          gh-pages -d dist
      